// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: gophkeeper/v1/gophkeeper.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{0}
}

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{1}
}

func (x *AuthRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *AuthRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type TokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{2}
}

func (x *TokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *TokenResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{3}
}

type LoginPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginPayload) Reset() {
	*x = LoginPayload{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginPayload) ProtoMessage() {}

func (x *LoginPayload) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginPayload.ProtoReflect.Descriptor instead.
func (*LoginPayload) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{4}
}

func (x *LoginPayload) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *LoginPayload) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginPayload) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type TextPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextPayload) Reset() {
	*x = TextPayload{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextPayload) ProtoMessage() {}

func (x *TextPayload) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextPayload.ProtoReflect.Descriptor instead.
func (*TextPayload) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{5}
}

func (x *TextPayload) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TextPayload) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type BinaryPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinaryPayload) Reset() {
	*x = BinaryPayload{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryPayload) ProtoMessage() {}

func (x *BinaryPayload) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryPayload.ProtoReflect.Descriptor instead.
func (*BinaryPayload) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{6}
}

func (x *BinaryPayload) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *BinaryPayload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CardPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Holder        string                 `protobuf:"bytes,1,opt,name=holder,proto3" json:"holder,omitempty"`
	Number        string                 `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	ExpMonth      string                 `protobuf:"bytes,3,opt,name=exp_month,json=expMonth,proto3" json:"exp_month,omitempty"`
	ExpYear       string                 `protobuf:"bytes,4,opt,name=exp_year,json=expYear,proto3" json:"exp_year,omitempty"`
	Cvv           string                 `protobuf:"bytes,5,opt,name=cvv,proto3" json:"cvv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardPayload) Reset() {
	*x = CardPayload{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardPayload) ProtoMessage() {}

func (x *CardPayload) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardPayload.ProtoReflect.Descriptor instead.
func (*CardPayload) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{7}
}

func (x *CardPayload) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

func (x *CardPayload) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *CardPayload) GetExpMonth() string {
	if x != nil {
		return x.ExpMonth
	}
	return ""
}

func (x *CardPayload) GetExpYear() string {
	if x != nil {
		return x.ExpYear
	}
	return ""
}

func (x *CardPayload) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Metadata      string                 `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Deleted       bool                   `protobuf:"varint,6,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Login         *LoginPayload          `protobuf:"bytes,7,opt,name=login,proto3" json:"login,omitempty"`
	Text          *TextPayload           `protobuf:"bytes,8,opt,name=text,proto3" json:"text,omitempty"`
	Binary        *BinaryPayload         `protobuf:"bytes,9,opt,name=binary,proto3" json:"binary,omitempty"`
	Card          *CardPayload           `protobuf:"bytes,10,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{8}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Item) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *Item) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Item) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Item) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *Item) GetLogin() *LoginPayload {
	if x != nil {
		return x.Login
	}
	return nil
}

func (x *Item) GetText() *TextPayload {
	if x != nil {
		return x.Text
	}
	return nil
}

func (x *Item) GetBinary() *BinaryPayload {
	if x != nil {
		return x.Binary
	}
	return nil
}

func (x *Item) GetCard() *CardPayload {
	if x != nil {
		return x.Card
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{9}
}

func (x *ListRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{10}
}

func (x *ListResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{11}
}

func (x *GetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Metadata      string                 `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Login         *LoginPayload          `protobuf:"bytes,4,opt,name=login,proto3" json:"login,omitempty"`
	Text          *TextPayload           `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	Binary        *BinaryPayload         `protobuf:"bytes,6,opt,name=binary,proto3" json:"binary,omitempty"`
	Card          *CardPayload           `protobuf:"bytes,7,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertRequest) Reset() {
	*x = UpsertRequest{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertRequest) ProtoMessage() {}

func (x *UpsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertRequest.ProtoReflect.Descriptor instead.
func (*UpsertRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{12}
}

func (x *UpsertRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpsertRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpsertRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *UpsertRequest) GetLogin() *LoginPayload {
	if x != nil {
		return x.Login
	}
	return nil
}

func (x *UpsertRequest) GetText() *TextPayload {
	if x != nil {
		return x.Text
	}
	return nil
}

func (x *UpsertRequest) GetBinary() *BinaryPayload {
	if x != nil {
		return x.Binary
	}
	return nil
}

func (x *UpsertRequest) GetCard() *CardPayload {
	if x != nil {
		return x.Card
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SinceVersion  int64                  `protobuf:"varint,1,opt,name=since_version,json=sinceVersion,proto3" json:"since_version,omitempty"`
	Items         []*Item                `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{14}
}

func (x *SyncRequest) GetSinceVersion() int64 {
	if x != nil {
		return x.SinceVersion
	}
	return 0
}

func (x *SyncRequest) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	ServerVersion int64                  `protobuf:"varint,2,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{15}
}

func (x *SyncResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SyncResponse) GetServerVersion() int64 {
	if x != nil {
		return x.ServerVersion
	}
	return 0
}

var File_gophkeeper_v1_gophkeeper_proto protoreflect.FileDescriptor

const file_gophkeeper_v1_gophkeeper_proto_rawDesc = "" +
	"\n" +
	"\x1egophkeeper/v1/gophkeeper.proto\x12\rgophkeeper.v1\"\a\n" +
	"\x05Empty\"?\n" +
	"\vAuthRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"v\n" +
	"\rTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\"\x0f\n" +
	"\rLogoutRequest\"X\n" +
	"\fLoginPayload\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"7\n" +
	"\vTextPayload\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\"?\n" +
	"\rBinaryPayload\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\x87\x01\n" +
	"\vCardPayload\x12\x16\n" +
	"\x06holder\x18\x01 \x01(\tR\x06holder\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\x12\x1b\n" +
	"\texp_month\x18\x03 \x01(\tR\bexpMonth\x12\x19\n" +
	"\bexp_year\x18\x04 \x01(\tR\aexpYear\x12\x10\n" +
	"\x03cvv\x18\x05 \x01(\tR\x03cvv\"\xe2\x02\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\tR\bmetadata\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\x12\x18\n" +
	"\adeleted\x18\x06 \x01(\bR\adeleted\x121\n" +
	"\x05login\x18\a \x01(\v2\x1b.gophkeeper.v1.LoginPayloadR\x05login\x12.\n" +
	"\x04text\x18\b \x01(\v2\x1a.gophkeeper.v1.TextPayloadR\x04text\x124\n" +
	"\x06binary\x18\t \x01(\v2\x1c.gophkeeper.v1.BinaryPayloadR\x06binary\x12.\n" +
	"\x04card\x18\n" +
	" \x01(\v2\x1a.gophkeeper.v1.CardPayloadR\x04card\"!\n" +
	"\vListRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\"9\n" +
	"\fListResponse\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.gophkeeper.v1.ItemR\x05items\"\x1c\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x98\x02\n" +
	"\rUpsertRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\tR\bmetadata\x121\n" +
	"\x05login\x18\x04 \x01(\v2\x1b.gophkeeper.v1.LoginPayloadR\x05login\x12.\n" +
	"\x04text\x18\x05 \x01(\v2\x1a.gophkeeper.v1.TextPayloadR\x04text\x124\n" +
	"\x06binary\x18\x06 \x01(\v2\x1c.gophkeeper.v1.BinaryPayloadR\x06binary\x12.\n" +
	"\x04card\x18\a \x01(\v2\x1a.gophkeeper.v1.CardPayloadR\x04card\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"]\n" +
	"\vSyncRequest\x12#\n" +
	"\rsince_version\x18\x01 \x01(\x03R\fsinceVersion\x12)\n" +
	"\x05items\x18\x02 \x03(\v2\x13.gophkeeper.v1.ItemR\x05items\"`\n" +
	"\fSyncResponse\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.gophkeeper.v1.ItemR\x05items\x12%\n" +
	"\x0eserver_version\x18\x02 \x01(\x03R\rserverVersion2\xd4\x01\n" +
	"\vAuthService\x12D\n" +
	"\bRegister\x12\x1a.gophkeeper.v1.AuthRequest\x1a\x1c.gophkeeper.v1.TokenResponse\x12A\n" +
	"\x05Login\x12\x1a.gophkeeper.v1.AuthRequest\x1a\x1c.gophkeeper.v1.TokenResponse\x12<\n" +
	"\x06Logout\x12\x1c.gophkeeper.v1.LogoutRequest\x1a\x14.gophkeeper.v1.Empty2\xff\x02\n" +
	"\fVaultService\x12?\n" +
	"\x04List\x12\x1a.gophkeeper.v1.ListRequest\x1a\x1b.gophkeeper.v1.ListResponse\x125\n" +
	"\x03Get\x12\x19.gophkeeper.v1.GetRequest\x1a\x13.gophkeeper.v1.Item\x12;\n" +
	"\x06Create\x12\x1c.gophkeeper.v1.UpsertRequest\x1a\x13.gophkeeper.v1.Item\x12;\n" +
	"\x06Update\x12\x1c.gophkeeper.v1.UpsertRequest\x1a\x13.gophkeeper.v1.Item\x12<\n" +
	"\x06Delete\x12\x1c.gophkeeper.v1.DeleteRequest\x1a\x14.gophkeeper.v1.Empty\x12?\n" +
	"\x04Sync\x12\x1a.gophkeeper.v1.SyncRequest\x1a\x1b.gophkeeper.v1.SyncResponseB(Z&gokeeper/internal/transport/grpc/pb;pbb\x06proto3"

var (
	file_gophkeeper_v1_gophkeeper_proto_rawDescOnce sync.Once
	file_gophkeeper_v1_gophkeeper_proto_rawDescData []byte
)

func file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP() []byte {
	file_gophkeeper_v1_gophkeeper_proto_rawDescOnce.Do(func() {
		file_gophkeeper_v1_gophkeeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gophkeeper_v1_gophkeeper_proto_rawDesc), len(file_gophkeeper_v1_gophkeeper_proto_rawDesc)))
	})
	return file_gophkeeper_v1_gophkeeper_proto_rawDescData
}

var file_gophkeeper_v1_gophkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_gophkeeper_v1_gophkeeper_proto_goTypes = []any{
	(*Empty)(nil),         // 0: gophkeeper.v1.Empty
	(*AuthRequest)(nil),   // 1: gophkeeper.v1.AuthRequest
	(*TokenResponse)(nil), // 2: gophkeeper.v1.TokenResponse
	(*LogoutRequest)(nil), // 3: gophkeeper.v1.LogoutRequest
	(*LoginPayload)(nil),  // 4: gophkeeper.v1.LoginPayload
	(*TextPayload)(nil),   // 5: gophkeeper.v1.TextPayload
	(*BinaryPayload)(nil), // 6: gophkeeper.v1.BinaryPayload
	(*CardPayload)(nil),   // 7: gophkeeper.v1.CardPayload
	(*Item)(nil),          // 8: gophkeeper.v1.Item
	(*ListRequest)(nil),   // 9: gophkeeper.v1.ListRequest
	(*ListResponse)(nil),  // 10: gophkeeper.v1.ListResponse
	(*GetRequest)(nil),    // 11: gophkeeper.v1.GetRequest
	(*UpsertRequest)(nil), // 12: gophkeeper.v1.UpsertRequest
	(*DeleteRequest)(nil), // 13: gophkeeper.v1.DeleteRequest
	(*SyncRequest)(nil),   // 14: gophkeeper.v1.SyncRequest
	(*SyncResponse)(nil),  // 15: gophkeeper.v1.SyncResponse
}
var file_gophkeeper_v1_gophkeeper_proto_depIdxs = []int32{
	4,  // 0: gophkeeper.v1.Item.login:type_name -> gophkeeper.v1.LoginPayload
	5,  // 1: gophkeeper.v1.Item.text:type_name -> gophkeeper.v1.TextPayload
	6,  // 2: gophkeeper.v1.Item.binary:type_name -> gophkeeper.v1.BinaryPayload
	7,  // 3: gophkeeper.v1.Item.card:type_name -> gophkeeper.v1.CardPayload
	8,  // 4: gophkeeper.v1.ListResponse.items:type_name -> gophkeeper.v1.Item
	4,  // 5: gophkeeper.v1.UpsertRequest.login:type_name -> gophkeeper.v1.LoginPayload
	5,  // 6: gophkeeper.v1.UpsertRequest.text:type_name -> gophkeeper.v1.TextPayload
	6,  // 7: gophkeeper.v1.UpsertRequest.binary:type_name -> gophkeeper.v1.BinaryPayload
	7,  // 8: gophkeeper.v1.UpsertRequest.card:type_name -> gophkeeper.v1.CardPayload
	8,  // 9: gophkeeper.v1.SyncRequest.items:type_name -> gophkeeper.v1.Item
	8,  // 10: gophkeeper.v1.SyncResponse.items:type_name -> gophkeeper.v1.Item
	1,  // 11: gophkeeper.v1.AuthService.Register:input_type -> gophkeeper.v1.AuthRequest
	1,  // 12: gophkeeper.v1.AuthService.Login:input_type -> gophkeeper.v1.AuthRequest
	3,  // 13: gophkeeper.v1.AuthService.Logout:input_type -> gophkeeper.v1.LogoutRequest
	9,  // 14: gophkeeper.v1.VaultService.List:input_type -> gophkeeper.v1.ListRequest
	11, // 15: gophkeeper.v1.VaultService.Get:input_type -> gophkeeper.v1.GetRequest
	12, // 16: gophkeeper.v1.VaultService.Create:input_type -> gophkeeper.v1.UpsertRequest
	12, // 17: gophkeeper.v1.VaultService.Update:input_type -> gophkeeper.v1.UpsertRequest
	13, // 18: gophkeeper.v1.VaultService.Delete:input_type -> gophkeeper.v1.DeleteRequest
	14, // 19: gophkeeper.v1.VaultService.Sync:input_type -> gophkeeper.v1.SyncRequest
	2,  // 20: gophkeeper.v1.AuthService.Register:output_type -> gophkeeper.v1.TokenResponse
	2,  // 21: gophkeeper.v1.AuthService.Login:output_type -> gophkeeper.v1.TokenResponse
	0,  // 22: gophkeeper.v1.AuthService.Logout:output_type -> gophkeeper.v1.Empty
	10, // 23: gophkeeper.v1.VaultService.List:output_type -> gophkeeper.v1.ListResponse
	8,  // 24: gophkeeper.v1.VaultService.Get:output_type -> gophkeeper.v1.Item
	8,  // 25: gophkeeper.v1.VaultService.Create:output_type -> gophkeeper.v1.Item
	8,  // 26: gophkeeper.v1.VaultService.Update:output_type -> gophkeeper.v1.Item
	0,  // 27: gophkeeper.v1.VaultService.Delete:output_type -> gophkeeper.v1.Empty
	15, // 28: gophkeeper.v1.VaultService.Sync:output_type -> gophkeeper.v1.SyncResponse
	20, // [20:29] is the sub-list for method output_type
	11, // [11:20] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_gophkeeper_v1_gophkeeper_proto_init() }
func file_gophkeeper_v1_gophkeeper_proto_init() {
	if File_gophkeeper_v1_gophkeeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gophkeeper_v1_gophkeeper_proto_rawDesc), len(file_gophkeeper_v1_gophkeeper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_gophkeeper_v1_gophkeeper_proto_goTypes,
		DependencyIndexes: file_gophkeeper_v1_gophkeeper_proto_depIdxs,
		MessageInfos:      file_gophkeeper_v1_gophkeeper_proto_msgTypes,
	}.Build()
	File_gophkeeper_v1_gophkeeper_proto = out.File
	file_gophkeeper_v1_gophkeeper_proto_goTypes = nil
	file_gophkeeper_v1_gophkeeper_proto_depIdxs = nil
}
